"""empty message

Revision ID: 8f29522fd448
Revises: 19698871d932
Create Date: 2018-05-05 21:49:37.388167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f29522fd448'
down_revision = '19698871d932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('user', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_url')
    op.drop_column('user', 'image_filename')
    # ### end Alembic commands ###
